GAWB-1072 - Update cromwell execution case class for 0.21 (#582)
* Update cromwell execution case class for 0.21

* Updated the WDL4s version to match Cromwell 21 hotfix branch

* Fixing an exception when running the tests:
java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected

This was caused something with scalaz dependency brought in by
cats in wdl4s v0.5.  This change opts to not bring in the other
dependencies from wdl4s.

* reverting unnecessary scala test version change